name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Build for Linux
      run: make build-linux

    - name: Build for Windows
      run: make build-windows

    - name: Build for macOS
      run: make build-darwin

    - name: Build for ARM
      run: make build-arm